#ifndef TCC_DATA_STRUCTURE_MULTIDIMENSIONAL_COMPACT_KD_TREE_HPP
#define TCC_DATA_STRUCTURE_MULTIDIMENSIONAL_COMPACT_KD_TREE_HPP

namespace tcc {

  namespace data_structure {

    

  }

}

#endif //TCC_DATA_STRUCTURE_MULTIDIMENSIONAL_COMPACT_KD_TREE_HPP
